os: linux
dist: xenial
language: python

env:
- TERRAFORM_VERSION=1.0.2 TERRAFORM_DOCS_VERSION=0.16.0

install:
  # Install pre-commit
  - pip install pre-commit

  # Install terraform
  - curl -Lo terraform.zip "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
  - unzip terraform.zip
  - mv terraform ${HOME}/bin/terraform

  # Install terraform-docs
  - curl -Lo ./terraform-docs.tar.gz "https://github.com/terraform-docs/terraform-docs/releases/download/v${TERRAFORM_DOCS_VERSION}/terraform-docs-v${TERRAFORM_DOCS_VERSION}-linux-amd64.tar.gz"
  - tar -xzf terraform-docs.tar.gz
  - mv terraform-docs ${HOME}/bin/terraform-docs

jobs:
  include:
    - stage: lint
      name: pre-commit hooks
      script:
        - pre-commit run --all-files --show-diff-on-failure

cache:
  pip: true
  directories:
    - $HOME/.cache/pre-commit
